[server]
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
backgroundColor = "rgba(246, 214, 206, 1)"

secondaryBackgroundColor = "rgba(253, 232, 213, 1)"



textColor = "rgba(60, 58, 61, 1)"   

font = "sans serif"